resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

secret:
  name: events-stack-db

config:
  DEBUG: "true"

  DB_HOST: postgres.eventstack-system.svc.cluster.local
  DB_PORT: "5432"
  DB_USER: test
  DB_PASS: test
  DB_NAME: testdb
  DB_PARAMS: "sslmode=disable&connect_timeout=5"
  DB_READY_TIMEOUT: "4m"