{{- if .Values.endpointSecret.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "resources-presenter.fullname" . }}-endpoint
  namespace: {{ .Release.Namespace }}
stringData:
  server-url: http://{{ include "resources-presenter.fullname" . }}.{{ .Release.Namespace }}.svc:{{ .Values.service.port }}
  insecure: "true"
{{- end }}
